steps:
- name: 'gcr.io/cloud-builders/yarn'
  args: ['install']
- name: 'gcr.io/cloud-builders/yarn'
  args: ['build']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'repl-api', '--trigger-http', '--runtime', 'nodejs10', '--entry-point', 'app', '--set-env-vars', 'NODE_ENV=production']
