name: Deploy GCF

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install and build
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: |
          yarn
          yarn build
        env:
          CI: "true"
      - name: Auth to GCP
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      - name: Deploy to cloud function
        uses: actions/gcloud/cli@master
        with:
          args: functions deploy repl-api --trigger-http --runtime nodejs10 --entry-point app --set-env-vars NODE_ENV=production --project croapp-dev
